name: Bug Report (fake)
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version(s) did you encounter this bug ?
      placeholder: ex. 5.0.0
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Also tell us, what did you expect to happen?
      placeholder: I encountered an exception which looks suspicious while ...
    validations:
      required: true
  - type: input
    id: reproducer
    attributes:
      label: Do you have a reproducer?
      description: |
        A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that
        has a build file that can be executed to reproduce the issue.
        
        Reproducers are very helpful for contributors and will likely help them fixing your bug faster.
      placeholder: Link to github project/gist
