name: Feature request (form)
description: Suggest a feature for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Read this first before creating an issue:

        - do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.
        - you shall create a feature request only when it is general purpose enough.
        - make sure that the feature is not already
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Give the simplest and best explanation.
    validations:
      required: true
  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: A list of use cases this feature will enable and the value it creates.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
        4. ...
    validations:
      required: false
  - type: input
    id: reproducer
    attributes:
      label: Do you have a reproducer?
      description: |
        A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that
        has a build file that can be executed to reproduce the issue.
        
        Reproducers are very helpful for contributors and will likely help them fixing your bug faster.
      placeholder: Link to github project/gist
    validations:
      required: false
